export default {
    address: {
        shipper: 'Shipper',
        consignee: 'Consignee',
        notify: 'NotifyParty',
        consignor: 'Consignor',
        information: ' Information',
        'Address Abbreviation': 'Address Abbreviation',
        'Address Name':'Address Name',
        'Address Code': 'Address Code',
        Contact: 'Contact',
        Tel: 'Tel',
        'Mobile phone': 'Mobile phone',
        email: 'Email',
        'Administrative Region': 'Administrative Region',
        Postcode: 'Postcode',
        address: 'Address',
        name: ' Name',
        ok: 'OK',
        cancel: 'Cancel',
        add: 'Add ',
        edit: 'Edit ',
        'This area does not support automatic address search mode':'This area does not support automatic address search mode',
        'Switch to manual input mode':'Switch to manual input mode',
        'Switch to automatic mode':'Switch to automatic mode',
        'House number':'House number',
        'Address query':'Address query',
        'add address': 'Add Adress',
        'Please Select': 'Please Select...',
        'Please Company name': 'Please fill in  Company name',
        'Please Address Abbreviation': 'Please fill in Address Abbreviation',
        'Please Address Name': 'Please fill in Address Name',
        'Please Contact': 'Please fill in Contact',
        'Please Area Code': 'Please fill in Area Code',
        'Please Tel': 'Please fill in Tel',
        'Please phone': 'Please fill in Mobile',
        'Please Postcode': 'Please fill in Postcode',
        'Please Administrative Region': 'Please fill in Administrative Region',
        'Please Address': 'Please fill in Address',
        'Please CityCode': 'Please fill in city code',
        'Please email': 'Please enter the correct email address',
        success: 'The operation was successful',
        'api.F.globalError':
      'An unknown exception occurred in the system, please contact the customer support team for assistance',
        'Please enter value in English': 'Please enter value in English',
        'Is this data shared at home and abroad':
      '(Is this data shared at domestic or international )',
        shippingAddress: {
            name: 'Place of receipt',
            info1: 'Please select the Place of receipt or',
            info2: 'Same as shipper‘s address',
        },
        receivingAddress: {
            name: 'place of delivery',
            info1: 'Please select the place of delivery or ',
            info2: 'Same as consignee‘s address',
        },
    },
    basic: {
        'basic.errorCode.00000': 'Success',
        'basic.errorCode.10003': 'Failed：Value error',
        'basic.errorCode.10006': 'Failed：DB error',
        'basic.errorCode.10007': 'Failed：Subjet ID needed',
        'basic.errorCode.10008': 'Failed：Subjet ID incorrect',
        'basic.errorCode.10009': 'Failed：Value cannot be empty',
        'basic.errorCode.10019': 'Related data missing ',
        'basic.errorCode.30001': 'Data cannot be found',
        'basic.errorCode.30002':
      'Query Falied:Data Quantity less than limit, please use another query',
        'basic.errorCode.40000':
      'Authentication failed,please contact administrator',
        'basic.errorCode.40002': 'Invalid  Token',
        'basic.errorCode.40010': 'Access  token  expired',
        'basic.errorCode.99999': 'System error,please contact administrator',
        'basic.errorCode.10010': 'Failed：Please enter correct value ',
        'basic.errorCode.10011': 'Failed：Data exist',
        'basic.errorCode.10012':
      'Failed:  No premission to edit other tenant data ',
        'basic.errorCode.10013': 'Failed:Data has been deleted',
        'basic.errorCode.10014': 'Failed: Data marked as "True" cannot be created ',
        'basic.errorCode.10015': 'Failed: Invalid email address',
        'basic.errorCode.10016': 'Failed: Cannot be deleted ',
        'basic.errorCode.10017': 'Delete completed',
        'basic.errorCode.10018': 'Failed:Data does not exist',
        'basic.errorCode.20000': 'JSON format incorrect',
        'basic.errorCode.20015': 'Object does not exist,please change as POST',
        'basic.errorCode.20016': 'Object exists,please change as POST',
        'basic.errorCode.20017': 'Query object multiple, please use major key',
        'basic.errorCode.20018': 'Please check parameter',
        'basic.errorCode.40001':
      'Cannot Find Unique User , Please Consider Using DomainName/TenantCode',
        'basic.errorCode.40003': 'Client Id  Is  Required',
        'basic.errorCode.40004': 'Tenant  is  expired  or  locked',
        'basic.errorCode.40005': 'Tenant  start  time  is  not  fit',
        'basic.errorCode.40012': 'Please  log in  again',
        'basic.errorCode.40013': 'Your  password  has  expired',
        'api.F.globalError':
      'An unknown exception occurred in the system, please contact the customer support team for assistance',
        'api.F.Unknown error': 'Unknown error,please contact administrator',

        'basic.errorCode.CONTACT_PARTNER_NAME_ALREADY_EXISTS':
      'Contact Person Already exists',
        'basic.errorCode.CONTACT_PARTNER_MAME_EMPTY':
      'Contact Person Name is Empty',
        'basic.errorCode.CONTACT_PARTNER_TYPE_EMPTY':
      'Contact Person Type is Empty',
        'basic.errorCode.CONTACT_PARTNER_NAME_ILLEGAL':
      'Contact Person Name  is  Illeagal',
        'basic.errorCode.CONTACT_PARTNER_EMAIL_ILLEGAL':
      'Contact Person Eamil  is  Illeagal',
        'basic.errorCode.CONTACT_ADDRESS_EMAIL_ILLEGAL':
      'Contact Person Address  is  Illeagal',
        'basic.errorCode.CONTACT_NOT_EXISTS': 'Contact Person Doesn\'t esxit',
        'basic.errorCode.CONTACT_ADDRESS_NOT_EXISTS':
      'Contact Person Address Doesn\'t esxit',
    },
};
