export default {
    '--juslink-primary-color': 'rgb(255, 197, 0)',
    '--juslink-primary-color-disabled': '#fff6a3',
    '--juslink-primary-color-hover': '#ffd429',
    '--juslink-primary-color-active': '#d99f00',
    '--juslink-primary-color-outline': 'rgba(255, 197, 0, 0.2)',
    '--juslink-primary-color-deprecated-bg': '#fffde6',
    '--juslink-primary-color-deprecated-border': '#ffed7a',
    '--juslink-primary-1': '#fffde6',
    '--juslink-primary-2': '#fff6a3',
    '--juslink-primary-3': '#ffed7a',
    '--juslink-primary-4': '#ffe252',
    '--juslink-primary-5': '#ffd429',
    '--juslink-primary-6': '#ffc500',
    '--juslink-primary-7': '#d99f00',
    '--juslink-primary-8': '#b37d00',
    '--juslink-primary-9': '#8c5e00',
    '--juslink-primary-10': '#664100',
    '--juslink-primary-color-deprecated-l-35': 'rgb(255, 238, 179)',
    '--juslink-primary-color-deprecated-l-20': 'rgb(255, 220, 102)',
    '--juslink-primary-color-deprecated-t-20': 'rgb(255, 209, 51)',
    '--juslink-primary-color-deprecated-t-50': 'rgb(255, 226, 128)',
    '--juslink-primary-color-deprecated-f-12': 'rgba(255, 197, 0, 0.12)',
    '--juslink-primary-color-active-deprecated-f-30': 'rgba(255, 253, 230, 0.3)',
    '--juslink-primary-color-active-deprecated-d-02': 'rgb(255, 252, 220)',
    '--juslink-success-color': 'rgb(111, 198, 119)',
    '--juslink-success-color-disabled': '#ebfaeb',
    '--juslink-success-color-hover': '#98d49c',
    '--juslink-success-color-active': '#52a15c',
    '--juslink-success-color-outline': 'rgba(111, 198, 119, 0.2)',
    '--juslink-success-color-deprecated-bg': '#f1fff0',
    '--juslink-success-color-deprecated-border': '#dfeddf',
    '--juslink-warning-color': 'rgb(255, 197, 0)',
    '--juslink-warning-color-disabled': '#fff6a3',
    '--juslink-warning-color-hover': '#ffd429',
    '--juslink-warning-color-active': '#d99f00',
    '--juslink-warning-color-outline': 'rgba(255, 197, 0, 0.2)',
    '--juslink-warning-color-deprecated-bg': '#fffde6',
    '--juslink-warning-color-deprecated-border': '#ffed7a',
    '--juslink-error-color': 'rgb(255, 108, 108)',
    '--juslink-error-color-disabled': '#fff2f0',
    '--juslink-error-color-hover': '#ff9794',
    '--juslink-error-color-active': '#d95055',
    '--juslink-error-color-outline': 'rgba(255, 108, 108, 0.2)',
    '--juslink-error-color-deprecated-bg': '#fff2f0',
    '--juslink-error-color-deprecated-border': '#ffe8e6',
    '--juslink-info-color': 'rgb(98, 148, 198)',
    '--juslink-info-color-disabled': '#ebf4fa',
    '--juslink-info-color-hover': '#8ab1d4',
    '--juslink-info-color-active': '#4771a1',
    '--juslink-info-color-outline': 'rgba(98, 148, 198, 0.2)',
    '--juslink-info-color-deprecated-bg': '#f0faff',
    '--juslink-info-color-deprecated-border': '#dfe7ed'
};